version: "3.5"

services:
  db:
    image: postgres:15-alpine
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data